package com.fowoco.server.task.domain;

public enum TaskType {
    RECONTRACT,
    EMPLOYMENT_PERIOD_EXTENSION,
    STAY_PERIOD_EXTENSION,
    DOCUMENT_REQUEST,
    WORKER_ONBOARDING,
    PAYROLL_EXPLANATION,
    EMPLOYMENT_CHANGE,
    WORK_INSTRUCTION
}
