package com.fowoco.server.audit.domain;

public enum AuditAction {
    TASK_CREATED,
    TASK_UPDATED,
    CHECKLIST_ITEM_UPDATED,
    TASK_CANCELLED,
    APPROVAL_REQUESTED,
    TASK_APPROVED,
    TASK_REJECTED,
    APPROVAL_INVALIDATED,
    EXTERNAL_SUBMISSION_RECORDED,
    EVIDENCE_RECORDED,
    TASK_COMPLETED,
    FILE_UPLOADED,
    WORKER_DOCUMENT_FILE_LINKED,
    DOCUMENT_REQUEST_DRAFT_SAVED,
    AI_RUN_CREATED,
    AI_RUN_ANSWERS_SUBMITTED,
    AI_RUN_CANDIDATES_DECIDED,
    OUTBOX_MANUAL_RETRY_REQUESTED,
    WORKER_LINK_RESPONSE_SUBMITTED,
    WORKER_LINK_ACCESSED,
    USER_AGREEMENTS_RECORDED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED
}
