package com.fowoco.server.audit.domain;

public enum AuditTargetType {
    TASK,
    APPROVAL_REQUEST,
    EXTERNAL_SUBMISSION,
    EVIDENCE,
    FILE,
    WORKER_DOCUMENT,
    DOCUMENT_REQUEST_DRAFT,
    AI_RUN,
    OUTBOX_EVENT,
    WORKER_LINK,
    USER_ACCOUNT,
    WORKER_IMPORT,
    COMPANY_SETTINGS,
    DOCUMENT_OCR_RUN,
    STAY_VERIFICATION
}
