package com.fowoco.server.audit.domain;

public enum AuditAction {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_CANCELLED,
    APPROVAL_REQUESTED,
    TASK_APPROVED,
    TASK_REJECTED,
    APPROVAL_INVALIDATED,
    EXTERNAL_SUBMISSION_RECORDED,
    EVIDENCE_RECORDED,
    TASK_COMPLETED
}
